'use client';

import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { logger } from '@/lib/logger';

interface ExportPDFAdvancedProps {
  title: string;
  author?: string;
  date?: string;
  tags?: string[];
  filename?: string;
  contentId?: string;
}

export default function ExportPDFAdvanced({
  title,
  author = 'Simple Blog',
  date = new Date().toLocaleDateString('zh-CN'),
  tags = [],
  filename = 'document',
  contentId = 'article-content'
}: ExportPDFAdvancedProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);

  const generatePDFCover = (pdf: jsPDF) => {
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    // 添加背景色
    pdf.setFillColor(245, 247, 250);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');

    // 添加标题
    pdf.setFontSize(24);
    pdf.setTextColor(30, 41, 59);
    const titleLines = pdf.splitTextToSize(title, pageWidth - 40);
    pdf.text(titleLines, pageWidth / 2, 80, { align: 'center' });

    // 添加作者和日期
    pdf.setFontSize(12);
    pdf.setTextColor(100, 116, 139);
    pdf.text(`作者: ${author}`, pageWidth / 2, 120, { align: 'center' });
    pdf.text(`日期: ${date}`, pageWidth / 2, 130, { align: 'center' });

    // 添加标签
    if (tags.length > 0) {
      pdf.text(`标签: ${tags.join(', ')}`, pageWidth / 2, 140, { align: 'center' });
    }

    // 添加分割线
    pdf.setDrawColor(226, 232, 240);
    pdf.setLineWidth(0.5);
    pdf.line(30, 160, pageWidth - 30, 160);

    // 添加底部信息
    pdf.setFontSize(10);
    pdf.setTextColor(148, 163, 184);
    pdf.text('Generated by Simple Blog', pageWidth / 2, pageHeight - 20, { align: 'center' });
  };

  const exportToPDF = async () => {
    setIsExporting(true);
    setExportProgress(10);

    try {
      // 获取要导出的内容
      const element = document.getElementById(contentId);
      if (!element) {
        throw new Error('未找到要导出的内容');
      }

      setExportProgress(20);

      // 创建一个克隆元素进行样式调整
      const clonedElement = element.cloneNode(true) as HTMLElement;
      clonedElement.style.width = '800px';
      clonedElement.style.padding = '40px';
      clonedElement.style.background = 'white';
      clonedElement.style.color = 'black';
      clonedElement.style.position = 'absolute';
      clonedElement.style.left = '-9999px';
      clonedElement.style.top = '0';
      document.body.appendChild(clonedElement);

      // 优化打印样式
      const styleChanges = () => {
        // 隐藏不需要的元素
        const hideElements = clonedElement.querySelectorAll('.no-pdf, button, .export-pdf-button');
        hideElements.forEach((el) => {
          (el as HTMLElement).style.display = 'none';
        });

        // 优化代码块
        const codeBlocks = clonedElement.querySelectorAll('pre');
        codeBlocks.forEach((pre) => {
          pre.style.whiteSpace = 'pre-wrap';
          pre.style.wordBreak = 'break-word';
          pre.style.fontSize = '12px';
          pre.style.background = '#f8f9fa';
          pre.style.padding = '16px';
          pre.style.borderRadius = '8px';
        });

        // 优化图片
        const images = clonedElement.querySelectorAll('img');
        images.forEach((img) => {
          img.style.maxWidth = '100%';
          img.style.height = 'auto';
          img.style.display = 'block';
          img.style.margin = '16px auto';
        });

        // 优化标题
        const headings = clonedElement.querySelectorAll('h1, h2, h3, h4, h5, h6');
        headings.forEach((heading) => {
          (heading as HTMLElement).style.pageBreakAfter = 'avoid';
          (heading as HTMLElement).style.marginTop = '24px';
          (heading as HTMLElement).style.marginBottom = '12px';
        });

        // 优化段落
        const paragraphs = clonedElement.querySelectorAll('p');
        paragraphs.forEach((p) => {
          p.style.lineHeight = '1.8';
          p.style.marginBottom = '16px';
        });

        // 优化列表
        const lists = clonedElement.querySelectorAll('ul, ol');
        lists.forEach((list) => {
          (list as HTMLElement).style.marginLeft = '24px';
          (list as HTMLElement).style.marginBottom = '16px';
        });

        // 优化引用块
        const quotes = clonedElement.querySelectorAll('blockquote');
        quotes.forEach((quote) => {
          (quote as HTMLElement).style.borderLeft = '4px solid #e5e7eb';
          (quote as HTMLElement).style.paddingLeft = '16px';
          (quote as HTMLElement).style.marginLeft = '0';
          (quote as HTMLElement).style.fontStyle = 'italic';
          (quote as HTMLElement).style.color = '#6b7280';
        });

        // 优化表格
        const tables = clonedElement.querySelectorAll('table');
        tables.forEach((table) => {
          table.style.width = '100%';
          table.style.borderCollapse = 'collapse';
          table.style.marginBottom = '16px';
        });

        const tableCells = clonedElement.querySelectorAll('td, th');
        tableCells.forEach((cell) => {
          (cell as HTMLElement).style.border = '1px solid #e5e7eb';
          (cell as HTMLElement).style.padding = '8px';
        });
      };

      styleChanges();
      setExportProgress(40);

      // 使用 html2canvas 生成图片
      const canvas = await html2canvas(clonedElement, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        windowWidth: 840,
        windowHeight: clonedElement.scrollHeight
      });

      setExportProgress(60);

      // 移除克隆的元素
      document.body.removeChild(clonedElement);

      // 创建 PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // 添加封面页
      generatePDFCover(pdf);
      pdf.addPage();

      setExportProgress(70);

      // 添加内容
      const imgData = canvas.toDataURL('image/png');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);
      const contentHeight = (canvas.height * contentWidth) / canvas.width;

      let heightLeft = contentHeight;
      let position = margin;

      // 添加第一页内容
      pdf.addImage(imgData, 'PNG', margin, position, contentWidth, contentHeight);
      heightLeft -= (pageHeight - margin * 2);

      setExportProgress(80);

      // 如果内容超过一页，添加更多页
      while (heightLeft > 0) {
        position = heightLeft - contentHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', margin, position, contentWidth, contentHeight);
        heightLeft -= (pageHeight - margin * 2);
      }

      setExportProgress(90);

      // 添加页码
      const totalPages = pdf.getNumberOfPages();
      for (let i = 2; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(10);
        pdf.setTextColor(148, 163, 184);
        pdf.text(`${i - 1} / ${totalPages - 1}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      }

      // 设置文档属性
      pdf.setProperties({
        title: title,
        subject: `Blog post: ${title}`,
        author: author,
        keywords: tags.join(', '),
        creator: 'Simple Blog PDF Exporter'
      });

      setExportProgress(95);

      // 保存 PDF
      const timestamp = new Date().toISOString().split('T')[0];
      pdf.save(`${filename}-${timestamp}.pdf`);

      setExportProgress(100);
      logger.info('PDF 导出成功', { title, filename });

      // 重置进度
      setTimeout(() => {
        setExportProgress(0);
      }, 1000);

    } catch (error) {
      logger.error('PDF 导出失败:', error);
      alert('PDF 导出失败，请稍后重试');
      setExportProgress(0);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="export-pdf-container no-pdf">
      <button
        onClick={exportToPDF}
        disabled={isExporting}
        className="inline-flex items-center px-3 py-1.5 border border-gray-300 dark:border-gray-600 text-sm font-medium rounded-md shadow-sm text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {isExporting ? (
          <>
            <svg
              className="animate-spin -ml-1 mr-2 h-4 w-4"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              ></circle>
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              ></path>
            </svg>
            导出中 {exportProgress > 0 && `${exportProgress}%`}
          </>
        ) : (
          <>
            <svg
              className="-ml-1 mr-2 h-4 w-4"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
            导出 PDF
          </>
        )}
      </button>

      {isExporting && exportProgress > 0 && (
        <div className="mt-2 w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
          <div
            className="bg-blue-600 h-2.5 rounded-full transition-all duration-300"
            style={{ width: `${exportProgress}%` }}
          ></div>
        </div>
      )}
    </div>
  );
}